#!/usr/bin/env bash


# Searches student code for a DIR_TO_COPY($1), and copies it to DESTINATION_JAVA_SRC($2)
# Called below
run_command () {
    COMMAND_TO_RUN=$1
    COMMAND_LABEL=$2
    COMMAND_TMP_FILE_NAME=$3
    RESULTS_FILE_NAME=$4
    MAXIMUM_POINTS=${5:-1}

    # Try to compile the maven project
    $COMMAND_TO_RUN 2>&1 | tee "/tmp/${COMMAND_TMP_FILE_NAME}.out"

    if [ ${PIPESTATUS[0]} -eq 0 ]
    then
        echo "[GS - Main Tests] ${COMMAND_LABEL} successful!"

        # Optionally output successful mvn compile message
        python3 "$PYTHON_JSON_TOOL" -m $MAXIMUM_POINTS -p -t "Step ${COMMAND_LABEL} successful" -i "/tmp/${COMMAND_TMP_FILE_NAME}.out" > "$OUTPUT_DIR"/"$RESULTS_FILE_NAME"
    else
        echo "[GS - Main Tests] ${COMMAND_LABEL} failed! Exiting..."
        python3 "$PYTHON_JSON_TOOL" -m $MAXIMUM_POINTS -t "Step ${COMMAND_LABEL} failed" -i "/tmp/${COMMAND_TMP_FILE_NAME}.out" > "$OUTPUT_DIR"/"$RESULTS_FILE_NAME"
    fi
}



# START: Sets correct directories based on local dev machine vs Gradescope production
if [ -f "/autograder/harness.py" ]; then
    echo "[GS] Running on Gradescope container, using Gradescope vars"
    DIR="/autograder/source"
    OUTPUT_DIR="/autograder/results"
    STUDENT_SUBMISSION_DIR="/autograder/submission"
else 
    echo "[GS] Running on local dev machine, using ./localautograder/ "
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    OUTPUT_DIR="$DIR/localautograder/results"
    mkdir -p $OUTPUT_DIR
    STUDENT_SUBMISSION_DIR="$DIR/localautograder/submission"
    mkdir -p $STUDENT_SUBMISSION_DIR
fi
PYTHON_JSON_TOOL="$DIR/tools/json_generator.py"
VITEST_JSON_TOOL="$DIR/tools/vitest_to_gradescope.py"

# END: Sets correct directories based on local dev machine vs Gradescope production

cd "$STUDENT_SUBMISSION_DIR"

rm -rf node_modules

run_command "npm ci" "npm install via npm ci" "npm_install" "results10.json" 0

run_command "npm run format" "proper formatting" "npm_run_format" "results_format.json" 1

run_command "npm run lint" "lint check" "npm_run_lint" "results_lint.json" 1

run_command "npm run typecheck" "type check" "npm_run_typecheck" "results_typecheck.json" 1

npm run test -- --reporter json --reporter default --outputFile.json=vitest_result.json

$VITEST_JSON_TOOL -i vitest_result.json -o "$OUTPUT_DIR"/"vitest_result.json"

